name: Run Unit Tests

on:
  pull_request:
    branches: [master] # Zakładając, że twoja główna gałąź nazywa się "main"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' # Lub inną wersję Node.js, której używasz

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm run test:unit
